# Generated by Django 4.1.3 on 2022-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30)], default=10),
        ),
    ]
