# Generated by Django 4.1.3 on 2022-12-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmainmodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolour',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='Product',
        ),
        migrations.AddField(
            model_name='productmainmodel',
            name='productcolour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolour'),
        ),
        migrations.AddField(
            model_name='productmainmodel',
            name='productimage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='productcolour',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], default='red', max_length=5),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
